# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jO2ms_B9x3LF0IOM3oatCKg3ncMZcpP8
"""

import pandas as pd

data = pd.read_csv(r"advertising.csv")

data.head()

data.info()

import matplotlib.pyplot as plt
plt.scatter(data['TV'], data['Sales'])
plt.xlabel('TV')

plt.ylabel('Sales')
plt.title('TV Advertising Budget vs Sales')

x=data['TV']
y=data['Sales']

def calculateavg(x):
    return sum(x)/len(x)

numsum=0
densum=0
avgvalx=calculateavg(x)
avgvaly=calculateavg(y)
for i in range(len(x)):
    temp1=x[i]-avgvalx
    temp2=y[i]-avgvaly
    numsum=numsum+temp1*temp2
    densum=densum+temp1*temp1

numsum,densum

m=numsum/densum
m

b=avgvaly-m*avgvalx
b

plt.scatter(x, y)
plt.plot(x, m*x+b, color='red')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.title('TV Advertising Budget vs Sales')
plt.show()

data.head()