# -*- coding: utf-8 -*-
"""simple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uer1hSiuD4ZNa4343o4qzGwlUGupqdH0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

wine_data = pd.read_csv("WineQT.csv")

print(wine_data.head())
print(wine_data.shape)
wine_data.info()

wine_data.isnull().sum()

wine_data.describe()

X_alcohol = wine_data[['alcohol']]
y = wine_data['quality']

X_train, X_test, y_train, y_test = train_test_split(
    X_alcohol, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

print(model.score(X_test, y_test))

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("Mean Squared Error:", mse)a
print("Mean Absolute Error:", mae)

plt.figure()
plt.scatter(X_test, y_test)
plt.plot(X_test, y_pred)
plt.xlabel("Alcohol")
plt.ylabel("Wine Quality")
plt.title("Best Fit Line: Alcohol vs Wine Quality")
plt.show()