# -*- coding: utf-8 -*-
"""Logistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDd5-6-Uw7fcqgQWD2ZzOUb5Xu8mJYb2
"""

import numpy as np

# sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# data
X = np.array([
    [1, 2],
    [2, 3],
    [3, 5],
    [6, 7],
    [7, 8],
    [8, 9]
])

y = np.array([0, 0, 0, 1, 1, 1])

# initialize
n, d = X.shape
w = np.zeros(d)
b = 0
lr = 0.1

# training
for _ in range(1000):
    z = np.dot(X, w) + b
    y_pred = sigmoid(z)

    dw = (1/n) * np.dot(X.T, (y_pred - y))
    db = (1/n) * np.sum(y_pred - y)

    w -= lr * dw
    b -= lr * db

# prediction
z = np.dot(X, w) + b
y_pred = sigmoid(z)
predictions = [1 if i > 0.5 else 0 for i in y_pred]

print("Predictions:", predictions)