# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeEBKk2kJ8jqkjPidXTqDtNOB93v9pif
"""

import pandas as pd
import math

data = pd.read_csv("KNNAlgorithmDataset.csv")

print(data.head())

data = data.drop(["id","Unnamed: 32"], axis=1)

data["diagnosis"] = data["diagnosis"].map({"M":1, "B":0})

dataset = data.values.tolist()

X = [row[1:] for row in dataset]
y = [row[0] for row in dataset]

test = X[0]

k = 5

distances = []

# Step 1: Find distance
for i in range(len(X)):

    d = 0
    for j in range(len(test)):
        d += (test[j] - X[i][j])**2

    d = math.sqrt(d)

    distances.append((d,y[i]))

distances.sort()

neighbors = distances[:k]

count = {0:0, 1:0}

for d,label in neighbors:
    count[label] += 1

prediction = max(count, key=count.get)

print("Prediction:", prediction)

import pandas as pd
import math
import random

data = pd.read_csv("KNNAlgorithmDataset.csv")

print(data.head())

data = data.drop(["id", "Unnamed: 32"], axis=1)

data["diagnosis"] = data["diagnosis"].map({"M":1, "B":0})

dataset = data.values.tolist()

random.shuffle(dataset)

split = int(0.8 * len(dataset))
train = dataset[:split]
test = dataset[split:]

X_train = [row[1:] for row in train]
y_train = [row[0] for row in train]

X_test = [row[1:] for row in test]
y_test = [row[0] for row in test]

n = len(X_train)
k = int(math.sqrt(n))

if k % 2 == 0:
  k=k+1
print("Value of K:", k)

def distance(a,b):
    d = 0
    for i in range(len(a)):
        d += (a[i] - b[i])**2
    return math.sqrt(d)

def knn_predict(test_point):

    distances = []


    for i in range(len(X_train)):
        d = distance(test_point, X_train[i])
        distances.append((d, y_train[i]))


    distances.sort()


    neighbors = distances[:k]

    count = {0:0, 1:0}

    for d,label in neighbors:
        count[label] += 1

    return max(count, key=count.get)

correct = 0

for i in range(len(X_test)):
    pred = knn_predict(X_test[i])

    if pred == y_test[i]:
        correct += 1

accuracy = correct / len(X_test)

print("Accuracy:", accuracy)

!pip install --upgrade numpy scipy scikit-learn

import scipy

print(scipy.__file__)
print(scipy.__version__)

import pandas as pd
import math
import random
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

data = pd.read_csv("KNNAlgorithmDataset.csv")

data = data.drop(["id", "Unnamed: 32"], axis=1)

data["diagnosis"] = data["diagnosis"].map({"M":1, "B":0})

dataset = data.values.tolist()

random.shuffle(dataset)

split = int(0.8 * len(dataset))
train = dataset[:split]
test = dataset[split:]

X_train = [row[1:] for row in train]
y_train = [row[0] for row in train]

X_test = [row[1:] for row in test]
y_test = [row[0] for row in test]

best_k = 1
best_score = 0

for k in range(1, 31, 2):
    model = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')
    avg_score = scores.mean()

    print("K =", k, "Cross Validation Accuracy =", avg_score)

    if avg_score > best_score:
        best_score = avg_score
        best_k = k

k = best_k
print("Best value of K:", k)

def distance(a,b):
    d = 0
    for i in range(len(a)):
        d += (a[i] - b[i])**2
    return math.sqrt(d)

def knn_predict(test_point):

    distances = []

    for i in range(len(X_train)):
        d = distance(test_point, X_train[i])
        distances.append((d, y_train[i]))

    distances.sort()

    neighbors = distances[:k]

    count = {0:0, 1:0}

    for d,label in neighbors:
        count[label] += 1

    return max(count, key=count.get)

correct = 0

for i in range(len(X_test)):
    pred = knn_predict(X_test[i])

    if pred == y_test[i]:
        correct += 1

accuracy = correct / len(X_test)

print("Accuracy:", accuracy)