# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtOcSdMp_i1ahp_7pDv075qOdcL2U2tw
"""

import pandas as pd
import math

df = pd.read_csv("play_tennis.csv")

df.head()

df = df.drop(columns=['day'])

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df.head()

def entropy(data):
    labels = data.iloc[:, -1]
    total = len(labels)

    counts = labels.value_counts()

    ent = 0

    for count in counts:
        p = count / total
        ent -= p * math.log2(p)

    return ent

def information_gain(data, feature):
    total_entropy = entropy(data)

    values = data[feature].unique()

    weighted_entropy = 0

    for value in values:
        subset = data[data[feature] == value]
        weighted_entropy += (len(subset) / len(data)) * entropy(subset)

    gain = total_entropy - weighted_entropy

    return gain

def best_feature(data):
    features = data.columns[:-1]

    gains = {}

    for feature in features:
        gains[feature] = information_gain(data, feature)

    best = max(gains, key=gains.get)

    return best

def majority_class(data):
    return data.iloc[:, -1].mode()[0]

def build_tree(data):

    labels = data.iloc[:, -1]

    # If all examples belong to one class
    if len(labels.unique()) == 1:
        return labels.iloc[0]

    # If no features remain
    if len(data.columns) == 1:
        return majority_class(data)

    best = best_feature(data)

    tree = {best: {}}

    for value in data[best].unique():

        subset = data[data[best] == value]

        if len(subset) == 0:
            tree[best][value] = majority_class(data)

        else:
            subset = subset.drop(columns=[best])

            tree[best][value] = build_tree(subset)

    return tree

decision_tree = build_tree(df)

print("Decision Tree:")
print(decision_tree)

def predict(tree, sample):
    if not isinstance(tree, dict):
        return tree

    feature = next(iter(tree))
    value = sample[feature]

    if value in tree[feature]:
        return predict(tree[feature][value], sample)
    else:
        return "Unknown"

train_data, test_data = train_test_split(
    df,
    test_size=0.3,
    random_state=42
)

tree = build_tree(train_data)

print("Decision Tree:")
print(tree)

train_predictions = []

for i in range(len(train_data)):
    sample = train_data.iloc[i]
    pred = predict(tree, sample)
    train_predictions.append(pred)

test_predictions = []

for i in range(len(test_data)):
    sample = test_data.iloc[i]
    pred = predict(tree, sample)
    test_predictions.append(pred)

train_actual = train_data.iloc[:, -1]
test_actual = test_data.iloc[:, -1]

train_acc = accuracy_score(train_actual, train_predictions)
test_acc = accuracy_score(test_actual, test_predictions)

print("Training Accuracy:", train_acc)
print("Testing Accuracy:", test_acc)

if train_acc > 0.90 and test_acc < 0.70:
    print("Result: Model is Overfitting")
elif train_acc < 0.70 and test_acc < 0.70:
    print("Result: Model is Underfitting")
else:
    print("Result: Model is Good ")