# -*- coding: utf-8 -*-
"""gradient_descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9jWlofKeoFxrne2JnaGKqUUJP3IGMj_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('advertising.csv')
data.head()

plt.scatter(data['TV'], data['Sales'])
plt.xlabel('TV')

plt.ylabel('Sales')
plt.title('TV Advertising Budget vs Sales')

X=data['TV']
Y=data['Sales']

X=(X-X.mean())/X.std()

m=0
b=0

L=0.01
epochs=1000
n=float(len(X))

for i in range(epochs):
    Y_pred=m*X+b
    Dm=(-2/n) * sum(X*(Y-Y_pred))
    Db=(-2/n) * sum(Y-Y_pred)
    m=m-L*Dm
    b=b-L*Db
print(m, b)

plt.scatter(X,Y)
plt.plot(X, m*X+b, color='red')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.title('TV Advertising Budget vs Sales')
plt.show()